name: Dependent

on: [pull_request]

jobs:
  setup-db:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Database
        run: |
          echo "Setting up database..."
          # Simulate setup time
          sleep 5
          echo "Database ready."

      - name: Initialize DB Schema
        run: echo "Initializing DB schema after setup."

  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Linter
        run: echo "Running linter on codebase..."

  build-and-test:
    runs-on: ubuntu-latest
    needs: [setup-db, lint-code] # This job waits for both setup-db and lint-code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: echo "Building project..."

      - name: Run tests
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: production
    steps:
      - name: Deploy app
        run: echo "Deploying app to production..."
