name: Envrionment Variables
os: [pull_request]

env:
  DAY_OF_WEEK: Monday

jobs:
  env-vars:
     runs-on: ubuntu-latest

     env:
       Greeting: Hello

     steps:
       - name: "Say Hello Mona it's Monday"
         run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
         env: 
            First_Name: Mona
