name: Secrets and Variables

on: [pull_request]

jobs:
  secrets-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Call api
        run: echo "calling ${{ vars.API_URL }} with key ${{ secrets.API_KEY }}"
